<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'admin' => '/../src/core/Admin.php',
                'area' => '/../src/core/Area.php',
                'auth' => '/../src/core/Auth.php',
                'candidato' => '/../src/core/Candidato.php',
                'categoria' => '/../src/core/Categoria.php',
                'db' => '/../src/core/db_conn.php',
                'empresa' => '/../src/core/Empresa.php',
                'errorresult' => '/../src/core/error.php',
                'mysessionhandler' => '/../src/core/sess_handler.php',
                'solicitud' => '/../src/core/Solicitud.php',
                'successresult' => '/../src/core/success.php',
                'vacante' => '/../src/core/Vacante.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
