<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'auth' => '/../src/core/Auth.php',
                'db' => '/../src/core/db_conn.php',
                'errorresult' => '/../src/core/error.php',
                'mysessionhandler' => '/../src/core/sess_handler.php',
                'successresult' => '/../src/core/success.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
