<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'area' => '/core/Area.php',
                'auth' => '/core/Auth.php',
                'auxiliaradmin' => '/core/AuxiliarAdmin.php',
                'candidato' => '/core/Candidato.php',
                'categoria' => '/core/Categoria.php',
                'ciudad' => '/core/Ciudad.php',
                'db' => '/core/db_conn.php',
                'empresa' => '/core/Empresa.php',
                'entidad' => '/core/EntidadFederativa.php',
                'errorresult' => '/core/error.php',
                'grado' => '/core/GradoEstudio.php',
                'municipio' => '/core/Municipio.php',
                'mysessionhandler' => '/core/sess_handler.php',
                'postulacion' => '/core/Postulacion.php',
                'solicitud' => '/core/Solicitud.php',
                'successresult' => '/core/success.php',
                'vacante' => '/core/Vacante.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
