<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'auth' => '/core/Auth.php',
                'db' => '/core/db_conn.php',
                'errorresult' => '/core/error.php',
                'mysessionhandler' => '/core/sess_handler.php',
                'successresult' => '/core/success.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
